# Name of the domain bridge, used for node naming and logging
name: my_bridge
from_domain: 2
to_domain: 3
topics:
  # Bridge "/clock" topic from doman ID 2 to domain ID 3
  clock:
    type: rosgraph_msgs/msg/Clock
  # Bridge "/chatter" topic from doman ID 2 to domain ID 3
  chatter:
    type: example_interfaces/msg/String
    # Override QoS reliablity setting to be best effort
    # This affects the domain bridge subscription and publisher
    # This does NOT effect the other "chatter" bridge below, which is for a different domain
    qos:
      reliability: best_effort
  # Also bridge "/chatter" topic from doman ID 2 to domain ID 4
  chatter:
    type: example_interfaces/msg/String
    to_domain: 4
  # Bridge "/chatter" topic from doman ID 2 to domain ID 3, but as "/chitter"
  chatter:
    type: example_interfaces/msg/String
    remap: chitter
